import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  bookSidebar: [
    {
      type: 'category',
      label: 'Preface',
      items: [
        'preface/intro',
        'preface/contributing',
        'preface/conventions',
        'preface/feedback',
        'preface/how-to-use',
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'Module-1',
    },
    {
      type: 'autogenerated',
      dirName: 'Module-2',
    },
    {
      type: 'autogenerated',
      dirName: 'Module-3',
    },
    {
      type: 'autogenerated',
      dirName: 'Module-4',
    },
    {
      type: 'doc',
      id: 'glossary',
      label: 'Glossary',
    },
  ],
};

export default sidebars;
